name: CTAN upload

inputs:
  filename:
    required: true
  dry-run:
    required: true
  uploader:
    required: true
  email:
    required: true
  version:
    required: false
    default: ${{ github.ref_name }}

runs:
  using: composite
  steps:
    - name: Send to CTAN
      uses: zauguin/ctan-upload@v0.1
      with:
        package-name: luaotfload
        version: ${{ inputs.version }}
        author: 'Marcel Krüger, LaTeX Project Team'
        uploader: ${{ inputs.uploader }}
        email: ${{ inputs.email }}
        license: lppl1.3
        summary: "Automatically generate MathML from LuaLaTeX math mode material"
        ctan-path: /macros/luatex/latex/luamml
        support: https://github.com/latex3/luamml/issues
        update: true
        topic: maths,luatex
        description: |
          LuaMML is an experimental package to automatically generate a MathML representation of mathematical expessions written in LuaLaTeX documents. These MathML representations can be used for improving accessibility or to ease conversion into new output formats like HTML.
        filename: ${{ inputs.filename }}
        dry-run: ${{ inputs.dry-run }}
        announcement-filename: ctan.ann
        note: Uploaded automatically by GitHub Actions.
